# 256x256.
lrate: 0.1
scale: 80
max-cycles: 4096 
min-basin: 0.00
map:
  dimension:
    - 256
    - 256
water:
  max-age: 1024
  evap-rate: 0.001
  deposition-rate: 0.05
  min-vol: 0.001
  entrainment: 10.0
  gravity: 2.0
  momentum-transfer: 1.0

# # 500x500.
# lrate: 0.1
# scale: 80
# max-cycles: 4000 
# min-basin: 0.00
# map:
#   dimension:
#     - 500
#     - 500
# water:
#   max-age: 1024
#   evap-rate: 0.001
#   deposition-rate: 0.05
#   min-vol: 0.001
#   entrainment: 10.0
#   gravity: 2.0
#   momentum-transfer: 1.0
